---
- name: prerequisites modules and sysctl
  become:      yes
  become_user: root
  become_flags: "-"
  block:

    - name: write to file modules for k8s
      copy:
        dest: "/etc/modules-load.d/k8s.conf"
        content: |
          overlay
          br_netfilter

    - name: write to file modules for k8s ipvs
      copy:
        dest: "/etc/modules-load.d/k8s-ipvs.conf"
        # for kernel > 4.19 nf_conntrac
        content: |
          ip_vs
          ip_vs_rr
          ip_vs_wrr
          ip_vs_sh
          nf_conntrack

    - name: write to file sysctl for k8s
      copy:
        dest: "/etc/sysctl.d/k8s.conf"
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: modprobe modules for k8s
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - overlay
        - br_netfilter
        - ip_vs
        - ip_vs_rr
        - ip_vs_wrr
        - ip_vs_sh
        - nf_conntrack

    - name: Set sysctl options k8s
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
      with_items:
        - { name: "net.bridge.bridge-nf-call-iptables",  value: 1 }
        - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
        - { name: "net.ipv4.ip_forward",                 value: 1 }

