---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 'master1'
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.4
          imagePullPolicy: IfNotPresent
          args:
            - "--storage.tsdb.retention.time=30d"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
            limits:
              cpu: 250m
              memory: 300Mi
          env:
          - name: TZ
            value: "Europe/Moscow"

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath:   prometheus.yml

            - name: prometheus-data
              mountPath: /prometheus/
      volumes:
        - name: config
          configMap:
            name: prometheus-cm
            defaultMode: 420

        - name: prometheus-data
          hostPath:
            path: /k8s_data/prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:      prometheus-cm
  namespace: monitoring
data:
  prometheus.yml: |
    ---
    global:
      scrape_interval:     5s
      #evaluation_interval: 15s

    scrape_configs:
    - job_name: 'worker1'
      scrape_interval: 1s
      static_configs:
        - targets: [ '192.168.0.134:9100' ]

    - job_name: 'worker2'
      scrape_interval: 1s
      static_configs:
        - targets: [ '192.168.0.135:9100' ]

---

