apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name:      node-exporter
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter
    spec:
      hostNetwork: true
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.0
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
          imagePullPolicy: IfNotPresent
          args:
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --path.procfs=/host/proc

            - --web.disable-exporter-metrics
            - --collector.disable-defaults
            - --collector.meminfo
            - --collector.cpu
            - --collector.cpu.info
            - --collector.cpufreq
            - --collector.netclass
            - --collector.netdev
            - --collector.netstat
            - --collector.hwmon
            - --collector.loadavg
            - --collector.filesystem
            - --collector.uname
            - --collector.diskstats
            - --collector.mountstats
            - --collector.stat

            - --no-collector.wifi

            - --collector.diskstats.device-exclude="^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\d+n\d+p)\d+$"
            - --collector.filesystem.mount-points-exclude="^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
            - --collector.filesystem.fs-types-exclude="^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"]

            - --collector.netclass.ignored-devices=^(veth.*)$

          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 250m
              memory: 200Mi
          env:
          - name: TZ
            value: "Europe/Moscow"

          volumeMounts:
          - mountPath: /host/sys
            name: sys
            mountPropagation: HostToContainer
            readOnly: true

          - mountPath: /host/root
            name: root
            mountPropagation: HostToContainer
            readOnly: true

          - mountPath: /host/proc
            name: proc
            mountPropagation: HostToContainer
            readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys

      - name: root
        hostPath:
          path: /

      - name: proc
        hostPath:
          path: /proc

