---
- name: kubeadm join
  become:      yes
  become_user: root
  become_flags: "-"
  block:
    - name: dbg info
      debug:
        msg: "--cri-socket={{ CRI.CRIO_SOCKET }} --token={{ k8s_join_token }} --discovery-token-ca-cert-hash={{ k8s_join_discovery_token }}"

    - name: kubeadm join
      shell: "kubeadm join {{ k8s_join_address }} --cri-socket={{ CRI.CRIO_SOCKET }} --token={{ k8s_join_token }} --discovery-token-ca-cert-hash={{ k8s_join_discovery_token }}"
      register: kubeadm_join_output

    - name: join debug info
      debug:
        msg: "{{kubeadm_join_output}}"

